version: "3"
services:
  rails-app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
      - cache

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rails_app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rails_db
  cache:
    image: redis:6
